# Create A Customer
POST https://task-event.herokuapp.com/customer/add
Content-Type: application/json

{
    "name":"samuel henry",
    "address":"",
    "mobileno":"",
    "email":""
}
### get all cust
GET  https://task-event.herokuapp.com/customer/
###
GET  https://task-event.herokuapp.com/customer/cus2020101682BC29D1B4D3407E9F28AAC66595AFF5
###del a customer
DELETE   https://task-event.herokuapp.com/cus2020101682BC29D1B4D3407E9F28AAC66595AFF5

### Customer END ####


### JOBS ###############
###Create A Job
POST http://localhost:5002/job/add
Content-Type: application/json

{
    "job_name":"sweeting",
    "client_id":"",
    "address":"Accra",
    "mobileno":"+233234",
    "start_date":"2020-10-11",
    "description":"",
    "website_url":"", 
    "resources":"" 
}
###
GET  https://task-event.herokuapp.com/job/<job_id>
###
GET  https://task-event.herokuapp.com/job/

###
DELETE   https://task-event.herokuapp.com/job/<job_id>
### JOBS END###############



###Reminder
POST https://task-event.herokuapp.com/reminder/add
Content-Type: application/json

{
    "service_type":"working",
    "job_id":"",
    "start_date":"",
    "interval":"",
    "end_date":""

}
### Return All Reminder
GET  https://task-event.herokuapp.com/reminder/<reminder_id>
###
DELETE https://task-event.herokuapp.com/reminder/<reminder_id>
###
GET  https://task-event.herokuapp.com/reminder/
###Reminder END
