POST http://localhost:5002/customer/add
Content-Type: application/json

{
    "name":"samuel henry",
    "address":"",
    "mobileno":"",
    "email":""
}
###
POST http://localhost:5002/jobs/add
Content-Type: application/json

{
    
}

###
GET  http://localhost:5002/jobs/
###
GET  http://localhost:5002/customer/cus20201016BEB86AC820A7461CBAD733E15C32592D

